# About
title: Eric Stein
name: Eric Stein
email: steinea@protonmail.com
description: >-
  Eric Stein is a game producer, publisher, designer, and researcher, located in the Fraser Valley of British Columbia. This site is a kind of digital garden, memex, or thought cabinet.
url: https://steinea.work
bluesky_username: steinea.bsky.social
github_username: steinea

# Build
plugins:
  - jekyll_custom_permalink
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ''
      type: pages
    values:
      permalink: /:basename/
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:year/:month/:day/:title/

# Exclusions
exclude:             ['_includes/notes_graph.json']
